import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {useRouter} from 'next/router'

export default function Home() {
  const router = useRouter()
  console.log('router---->', router)
  return (
    <div className={styles.container}>
      <Head>
        <title>Devter 🐧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Devter</a>
        </h1>
        <nav className={styles.nav}>
          <Link href='/timeline'><a>timeline</a></Link>
        </nav>
        
        <h3 className={styles.another_title}>Otro titulo</h3>
      </main>
        
    </div>
  )
}
